mysql:
  db: chatnio
  host: db4free.net
  password: ww123123
  port: 3306
  user: dahai913
  tls: true

redis:
  host: redis-11843.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com
  port: 11843
  db: huatai-free-db
  password: "zZ147258369@"


secret: secret
serve_static: true

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
